version: 2

references:

base_image: &base_image
  hashicorp/terraform:0.11.13

default_config: &default_config
  docker:
    - image: *base_image

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - checkout
    - *terraform_init
    - run:
        name: terraform apply
        command: |
          terraform apply --auto-approve

jobs:

  plan:
    <<: *default_config
    steps:
      - checkout
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            terraform plan

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - plan
      - approve:
          type: approval
          requires:
            - plan
      - apply-with-approval:
          requires:
            - approve