version: 2
aliases:
- image: hashicorp/terraform:0.11.13
jobs:
    terraform:
      docker:
      - image: hashicorp/terraform:0.11.13
      steps:
      - checkout
    plan:
      requires:
        - terraform
        - run:
          name: Terraform Plan
          command: |
            chmod +x ./terraformplan.sh
            sh ./terraformplan.sh

            
workflows: 
  version: 2
  Execute:
    jobs:
    - terraform
    - plan
