version: 2

references:

base_image: &base_image
  hashicorp/terraform:0.11.13

working_directory: &working_directory
  ~/tmp

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - checkout
    - *terraform_init
    - attach_workspace:
        at: tmp/workspace
    - run:
        name: terraform apply
        command: |
          terraform apply --auto-approve tmp/workspace/terraform.plan

jobs:

  plan:
    <<: *default_config
    steps:
      - checkout
      - *terraform_init
      - run:
          name: copying creds
          command: |
            #mkdir ~/.aws/test echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID_PROD\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_PROD\n" > ~/.aws/test/credentials
            cat ~/.aws/config
      - run:
          name: terraform plan
          command: |
            mkdir -p workspace
            terraform plan -out=workspace/terraform.plan
      - persist_to_workspace:
          root: workspace
          paths:
            - terraform.plan

  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - plan
#      - approve:
#          type: approval # Manual Approval Step
#          requires:
 #           - plan
   #   - apply-with-approval:
  #        requires:
   #         - approve