version: 2

aliases:
  - &terraform-image
    image: hashicorp/terraform:0.11.13

jobs:
  plan:
    docker:
      - *terraform-image
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            chmod +x ./terraformplan.sh
            sh ./terraformplan.sh
  apply:
    docker:
      - *terraform-image
    steps:
      - checkout
      - run:
          name: Terraform apply
          command: |
            chmod +x ./terraformapply.sh
            sh ./terraformapply.sh

workflows:
  version: 2
  plan and apply:
    jobs:
      - plan
      - apply